
- ros_topic_name: "/clock"
  gz_topic_name: "/world/default/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# -------- RGB camera (right) --------
- ros_topic_name: "/cam_0/image_raw"
  gz_topic_name: "/world/default/model/x500_depth_1/link/camera_link/sensor/stereo_right/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/cam_0/camera_info"
  gz_topic_name: "/world/default/model/x500_depth_1/link/camera_link/sensor/stereo_right/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# -------- RGB camera (left) --------
- ros_topic_name: "/cam_1/image_raw"
  gz_topic_name: "/world/default/model/x500_depth_1/link/camera_link/sensor/stereo_left/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/cam_1/camera_info"
  gz_topic_name: "/world/default/model/x500_depth_1/link/camera_link/sensor/stereo_left/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# -------- IMU --------
- ros_topic_name: "/x500_depth_1/imu"
  gz_topic_name: "/world/default/model/x500_depth_1/link/base_link/sensor/imu_sensor/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS